#!/bin/bash
BASEDIR=$(dirname "$0")

cd "$BASEDIR/terraform" || exit
terraform init
terraform apply

# ping "$IP"

# cd "$BASEDIR/ansible" || exit
# ansible-galaxy install -f -r requirements.yml
# ansible-playbook main.yml -i inventory/hosts.yml -K

cd "$BASEDIR/terraform" || exit
terraform destroy
