# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "kenc/debian-11.5"
  config.vm.box_url = "file://../builds/base.libvirt.box"

  config.nfs.verify_installed = false
  config.vm.synced_folder '.', '/vagrant', disabled: true
end
