{
 "title": "Backups",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "restic_backup_success", "legendFormat": "Time" }
   ]
  },
  {
   "title": "Total Backup Size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(backend) (restic_repo_bytes_total) / 1000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    { "expr": "restic_repo_duration_seconds", "legendFormat": "{{location}} {{backend}}" }
   ]
  },
  {
   "title": "Last Run",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "time: DD-MM-YYYY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "restic_backup_latest_datetime * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Added",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum by(backend) (restic_repo_bytes_added / 1000000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Files Processed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(state) (restic_repo_files)",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}