#!/bin/bash

set -euo pipefail

DISK=""
DISK_UUID="$(lsblk -nlo UUID $DISK)"
MOUNT_DIR="/mnt/kd"
CONFIG_DIR=""
AUTORESTIC_CONFIG_FILE="$CONFIG_DIR/.autorestic.yml"
AUTORESTIC_LOG_FILE="$CONFIG_DIR/logs/autorestic.log"

if [ ! -e "$AUTORESTIC_LOG_FILE" ]; then
	mkdir -p "$(dirname $AUTORESTIC_LOG_FILE)"
	touch "$AUTORESTIC_LOG_FILE"
fi

# redirect output
exec &> >(tee -a "${AUTORESTIC_LOG_FILE}")

echo "==========================================="
echo "| Starting backup at $(date '+%Y-%m-%d %H:%M:%S') | "
echo "==========================================="
SECONDS=0

# mount
echo "Mounting backup disk $DISK"
mount "/dev/disk/by-uuid/$DISK_UUID" "$MOUNT_DIR"

autorestic -c "$AUTORESTIC_CONFIG_FILE" backup -av --ci

# unmount
echo "Unmounting backup disk $DISK"
umount "$MOUNT_DIR"

duration="$SECONDS"
echo "Backup completed in $((duration / 60))m $((duration % 60))s"
echo ""
