#!/bin/bash

CREDS_FILE="./secrets.sh"
RESTIC_REPOSITORY="b2:[repo-name]/restic"
SNAPSHOT_ID=""  # latest or specific id
TARGET_DIR=""
RESTORE_DIR=""

source "$CREDS_FILE"

# restic -r "$RESTIC_REPOSITORY" snapshots  # check for snapshot id
restic -r "$RESTIC_REPOSITORY" restore "$SNAPSHOT_ID" --target "$TARGET_DIR" --include "$RESTORE_DIR"
