#!/bin/bash

VERSION="0.9.6"
RESTIC_DIR="/home/restic/bin"

useradd -m restic
mkdir -p $RESTIC_DIR
curl -L https://github.com/restic/restic/releases/download/v$vERSION/restic_$VERSION_linux_amd64.bz2 | bunzip2 > $RESTIC_DIR/restic

chown root:restic $RESTIC_DIR/restic
chmod 750 $RESTIC_DIR/restic

setcap cap_dac_read_search=+ep $RESTIC_DIR/restic
